In [7]:
import numpy as np
t = ( 10, 20, 30, 40, 50 )
tt = np.array( t )
print( type( tt ) )
print( tt )

l = [ 10, 20, 30, 40, 50 ]
ll = np.array( l )
print( type( ll ) )
print( ll )

s = { 10, 20, 30, 40, 50 }
print( type( s ) )
ss = np.array( s )
print( type( ss ) )

<class 'numpy.ndarray'>
[10 20 30 40 50]
<class 'numpy.ndarray'>
[10 20 30 40 50]
<class 'set'>
<class 'numpy.ndarray'>


In [20]:
n = np.array( [87, 45, 23, 85, 84, 54, 61, 37, 24, -79] )
print( n.shape )                       # (10,)  1차원 배열        (10,1) 10행 1열 2차원 배열
print( np.abs( n ) )                   # 절대값
print( np.sqrt( np.abs( n ) ) )        # 제곱근
print( np.square( n ) )                # 제곱
print( np.isnan( n ) )                 # Not a Number
print( np.sum( n ) )
print( np.mean( n ) )
print( np.max( n ) )
print( np.min( n ) )
print( np.sort( n ) )
print( np.sort( n )[::-1] )

(10,)
[87 45 23 85 84 54 61 37 24 79]
[9.32737905 6.70820393 4.79583152 9.21954446 9.16515139 7.34846923
 7.81024968 6.08276253 4.89897949 8.88819442]
[7569 2025  529 7225 7056 2916 3721 1369  576 6241]
[False False False False False False False False False False]
421
42.1
87
-79
[-79  23  24  37  45  54  61  84  85  87]
[ 87  85  84  61  54  45  37  24  23 -79]


In [33]:
m = [ [1, 2, 3], [4, 5, 6] ]
print( type( m ) )
mm = np.array( m  )
print( type( mm ) )
print( mm.shape )                        # (2,3)
print( mm )

mm = mm.reshape( 3, 2 )
print( mm )

# mm = mm.reshape( 3, 3 )         # 에러
# mm = mm.reshape( 2, 2 )         # 에러

w = [87, 45, 23, 85, 84, 54, 61, 37, 24, -79]
ww = np.array( w ).reshape( 5, 2 )
print( ww )

<class 'list'>
<class 'numpy.ndarray'>
(2, 3)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[ 87  45]
 [ 23  85]
 [ 84  54]
 [ 61  37]
 [ 24 -79]]


In [52]:
m = [ i for i in range( 1, 10 ) ]
print( type( m ) )
m = np.array( m ).reshape( 3, 3 )
print( m )
print( m.sum() )
print( m.sum( axis=0 ) )      # 열기준
print( m.sum( axis=1 ) )      # 행기준
print( m.mean() )
print( m.mean( axis=0 ) )
print( m.mean( axis=1 ) )

# 편차(deviation)                관측값에서 평균 또는 중앙값을 뺀 것이다.
# 분산(variance)                 편차를 제곱하고 평균을 구한다. 차이값의 제곱의 평균이다. 
# 표준 편차(standard deviation)  제곱해서 값이 부풀려진 분산을 제곱근해서 다시 원래 크기로 만든다.

print( np.var( m ) )             # 분산
print( np.std( m ) )             # 표준편차
print( np.std( m, axis=0 ) )     # 표준편차

print( np.max( m ) )
print( np.min( m ) )
print( np.max( m, axis=0 ) )
print( np.max( m, axis=1 ) )

<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
5.0
[4. 5. 6.]
[2. 5. 8.]
6.666666666666667
2.581988897471611
[2.44948974 2.44948974 2.44948974]
9
1
[7 8 9]
[3 6 9]


In [68]:
m = np.array( [[1, 2, 3], [4, 5, 6], [7, 8, 9]] )
w = np.array( [[9, 8, 7], [6, 5, 4], [3, 2, 1]] )
print( m )
print( w )
# print( np.add( m, w ) )
# print( np.subtract( m, w ) )
# print( np.multiply( m, w ) )       # 곱셈
# print( np.divide( m, w ) )

print( m + w )
print( m - w )
print( m * w )
print( m / w )
print( m * 2 )
print( m ** 2 )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [97]:
a = np.array( [1, 2, 3] )             # 벡터
b = np.array( [4, 5, 6] )
print( np.dot( a, b, ) )              # 1*4 + 2*5 + 3*6

print( np.zeros( 10 ) )
print( np.zeros( (3, 3) ) )
print( np.ones( (3, 3) ) )

a = np.random.randn( 10 )
# print( a )
b = np.random.randn( 10 )
print( np.maximum( a, b ) )
print( np.minimum( a, b ) )

m = np.random.randn( 5, 5 )
# print( m )
print( np.sum( m ) )
print( np.sum( m, axis=0 ) )
print( np.sum( m, axis=1 ) )

32
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 0.03109398  1.13497723 -0.40257204  1.83569306  0.42601983  0.62690617
  0.82146154  0.22471385  0.59177187  1.47228722]
[-0.69648412  0.84298946 -0.99613002 -1.31404216  0.00665941 -1.79827017
 -1.21879253 -0.07066536 -0.68668185  0.80174878]
1.4420223142936623
[-0.07613818  1.89768933 -1.61008749  0.88161069  0.34894797]
[ 6.95900466e-01  1.27030988e-03  3.89425396e-01  2.18691473e+00
 -1.83148859e+00]


In [111]:
a = [i for i in range( 10, 20 ) ]
# print( type( a ) )                    # list
print( a[0:5] )
print( a[:-1])
print( a[3:])

b = np.arange( 10, 20 )
# print( type( b ) )                    # numpy.ndarray
print( b[0:5] )
print( b[:-1])
print( b[3:])

[10, 11, 12, 13, 14]
[10, 11, 12, 13, 14, 15, 16, 17, 18]
[13, 14, 15, 16, 17, 18, 19]
[10 11 12 13 14]
[10 11 12 13 14 15 16 17 18]
[13 14 15 16 17 18 19]


In [142]:
a = [ [1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15] ]
# print( type( a ) )
print( a[2][2] )
print( a[:][:] )
print( a[2][:])
print( a[0:2][0:2] )                    # [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
# print( a[0:2,0:2] )                   # 에러

print()
b = np.array( np.arange( 1, 16 ) ).reshape( 3, 5 )
# print( type( b ) )
print( b[2][2] )                                   
print( b[:][:] )
print( b[2][:])  
print( b[0:2][0:2] )                     # [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

print( b[0:2, 0:2])
print( b[:-1,:-1])
print( b[1:2,:])
print( b[2, 2] )

13
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
[11, 12, 13, 14, 15]
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

13
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2]
 [6 7]]
[[1 2 3 4]
 [6 7 8 9]]
[[ 6  7  8  9 10]]
13
